Create 13-mount-checker

diff --git a/bash/etc/update-motd.d/13-mount-checker b/bash/etc/update-motd.d/13-mount-checker
--- a/bash/etc/update-motd.d/13-mount-checker
+++ b/bash/etc/update-motd.d/13-mount-checker
@@ -1,18 +1,21 @@
 #!/bin/bash
 
 function mountChecker() {
-    ls $1 > /dev/null 2>&1
-    if [ $? = "0" ];
-    then
-        if [ "$(ls -Al $1 | egrep '^-|d' | wc -l)" -ge 0 ];
+    for arg in $@
+    do
+        ls $arg > /dev/null 2>&1
+        if [ $? = "0" ];
         then
-            echo -e "\033[0;32m[mounted]\033[0m $1"
+            if [ "$(ls -Al $arg | egrep '^-|d' | wc -l)" != '0' ];
+            then
+                echo -e "\033[0;32m[mounted]\033[0m $arg"
+            else
+                echo -e "\033[1;33m[empty]\033[0m   $arg"
+            fi
         else
-            echo -e "\033[1;31m[failed]\033[0m  $1"
+            echo -e "\033[1;31m[failed]\033[0m  $arg"
         fi
-    else
-        echo -e "\033[1;31m[failed]\033[0m  $1"
-    fi
+    done
 }
 
 echo "Mount checker:"
